*FULL MODEL;

ODS HTML;
PROC REG DATA=DATA_TRAIN;
MODEL Y = X1 X2 X3 X4 INTER_X5_X6;
RUN;
ODS HTML CLOSE;

*Model Selection Criterion;
PROC REG DATA=CDI OUTEST=FITS; 
MODEL LPHYS = TOT_INCOME LAND_AREA POP_ELDERLY BEDS 
CRIMES HSGRAD UNEMPLOY 
/CLI SELECTION=RSQUARE ADJRSQ CP AIC SBC B BEST=3; 
RUN;



*Automated Selection methods;
PROC REG DATA=DATA_TRAIN OUTEST=FITS; 
MODEL Y = X1 X2 X3 X4 INTER_X5_X6 
/CLI SELECTION=FORWARD; 
RUN;

PROC REG DATA=DATA_TRAIN OUTEST=FITS; 
MODEL Y = X1 X2 X3 X4 INTER_X5_X6 
/CLI SELECTION=FORWARD; 
RUN;

PROC REG DATA=DATA_TRAIN OUTEST=FITS; 
MODEL Y = X1 X2 X3 X4 INTER_X5_X6 
/CLI SELECTION=FORWARD; 
RUN;



*Model Validation;
ODS HTML;
PROC REG DATA=DATA_TEST;
MODEL Y = X1 X2 X3 X4 INTER_X5_X6;
RUN;
ODS HTML CLOSE;
